export type PermissionsType =
  | "anamneseForm"
  | "autoRecording"
  | "autojoin"
  | "cameraRequired"
  | "chatEnabled"
  | "commandCenter"
  | "conferenceRoom"
  | "downloadVideoReportEnabled"
  | "jwtRequired"
  | "manageOrganizations"
  | "schedule"
  | "sendAgreement"
  | "shareLink"
  | "videoReport"
  | "waitingList";
